#!/bin/sh

/docker-entrypoint.sh elasticsearch \
	-Des.script.inline=on \
	-Des.script.indexed=on \
	-Des.threadpool.search.type=fixed \
	-Des.threadpool.search.size=20 \
	-Des.threadpool.search.queue_size=10000 \
	-Des.threadpool.search.type=cached &

cd /opt/Hippocampe/core
python app.py
